version: "2"
services:
  data:
    build: ./data
    volumes:
      - ../:/data
  mysql:
    image: mysql:5.7
    volumes_from:
        - data
    volumes:
        - ../data/mysql:/var/lib/mysql
        - "./mysql/init:/docker-entrypoint-initdb.d"
    environment:
        - MYSQL_ROOT_PASSWORD=root
    container_name: chatbot_mysql
    ports:
      - "3307:3306"
  # mysql2:
  #   image: mysql:5.7
  #   volumes_from:
  #       - data
  #   volumes:
  #       - ../data/mysql2:/var/lib/mysql
  #       - "./mysql2/init:/docker-entrypoint-initdb.d"
  #   environment:
  #       - MYSQL_ROOT_PASSWORD=root
  #   container_name: mysql2
  #   ports:
  #     - "3308:3306"
  fpm:
    build: ./fpm
    volumes_from:
      - data
    links:
      - mysql
    container_name: chatbot_fpm
  nginx:
    build: ./nginx
    volumes_from:
      - data
    links:
      - fpm:fpm
      - mysql
    ports:
      - "8010:80"
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_NAME=chatbot
    container_name: chatbot_nginx
  composer:
    build: ./composer
    volumes_from:
      - data
    container_name: chatbot_composer
        #  gulp:
        #    build: ./gulp
        #    volumes_from:
        #      - data
        #  npm:
        #    build: ./npm
        #    volumes_from:
        #      - data
